"""
Alert generation and management.

Alerts are generated by comparing consecutive risk snapshots and
drift results. The four alert types are:
  DRIFT_DETECTED    — KS-test flagged a volatility regime shift
  DRIFT_RESOLVED    — drift flag cleared after being set
  RISK_LEVEL_CHANGE — symbol crossed a quantile threshold boundary
  VOLATILITY_SPIKE  — rolling volatility rose > 30% in 5 sessions
"""
import uuid
from datetime import datetime

from sqlalchemy.orm import Session

from ..db import Alert, UserAlertState, WatchlistItem

# ── Alert generation ──────────────────────────────────────────────

def generate_alerts(db: Session, symbol: str, snapshot: dict, previous_snapshot: dict | None) -> None:
    """
    Compare a new snapshot against the previous one and write any
    triggered alerts to the database.
    """
    if not snapshot:
        return


    # 1. Drift detected
    if snapshot.get("driftFlag") and not (previous_snapshot or {}).get("driftFlag"):
        score = snapshot.get("driftScore", 0.0)
        severity = "HIGH" if score > 0.5 else "MEDIUM"
        _write_alert(
            db, symbol, "DRIFT_DETECTED", severity,
            "Volatility regime shift detected",
            f"KS-test flagged a distribution divergence. Normalised mean shift: {score:.4f}. "
            f"Recent volatility ({snapshot['currentVolatility']:.4f}) has moved significantly "
            f"from the 180-day reference window.",
        )

    # 2. Drift resolved
    if not snapshot.get("driftFlag") and (previous_snapshot or {}).get("driftFlag"):
        _write_alert(
            db, symbol, "DRIFT_RESOLVED", "LOW",
            "Drift flag cleared",
            "KS-test is no longer significant. The recent volatility distribution "
            "has converged back towards the reference window.",
        )

    # 3. Risk level change
    prev_risk = (previous_snapshot or {}).get("currentRisk")
    curr_risk = snapshot.get("currentRisk")
    if prev_risk and curr_risk and prev_risk != curr_risk:
        severity = "HIGH" if curr_risk == "HIGH" else "MEDIUM" if curr_risk == "MEDIUM" else "LOW"
        _write_alert(
            db, symbol, "RISK_LEVEL_CHANGE", severity,
            f"Risk level changed: {prev_risk} → {curr_risk}",
            f"Current volatility ({snapshot['currentVolatility']:.4f}) crossed the "
            f"{'P80' if curr_risk == 'HIGH' else 'P50'} quantile threshold.",
        )

    # 4. Volatility spike — vol rose > 30% vs previous
    prev_vol = (previous_snapshot or {}).get("currentVolatility", 0)
    curr_vol = snapshot.get("currentVolatility", 0)
    if prev_vol > 0 and curr_vol > 0 and (curr_vol - prev_vol) / prev_vol > 0.30:
        pct = ((curr_vol - prev_vol) / prev_vol) * 100
        _write_alert(
            db, symbol, "VOLATILITY_SPIKE", "MEDIUM",
            f"Volatility spike detected (+{pct:.0f}%)",
            f"Rolling 20-day volatility rose from {prev_vol:.4f} to {curr_vol:.4f}. "
            f"This may indicate an emerging risk regime change.",
        )


def _write_alert(db: Session, symbol: str, alert_type: str, severity: str,
                 message: str, detail: str) -> None:
    existing = (
        db.query(Alert)
        .filter_by(symbol=symbol, type=alert_type, read=False)
        .first()
    )
    if existing:
        return

    alert = Alert(
        id=str(uuid.uuid4()),
        timestamp=datetime.utcnow(),
        symbol=symbol,
        type=alert_type,
        severity=severity,
        message=message,
        detail=detail,
        read=False,
    )
    db.add(alert)
    db.commit()


# ── Alert retrieval ───────────────────────────────────────────────

def get_alerts(db: Session, limit: int = 100) -> list[dict]:
    """Return the most recent alerts, newest first."""
    rows = (
        db.query(Alert)
        .order_by(Alert.timestamp.desc())
        .limit(limit)
        .all()
    )
    return [{
        "id":        a.id,
        "timestamp": a.timestamp.isoformat() + "Z",
        "symbol":    a.symbol,
        "type":      a.type,
        "severity":  a.severity,
        "message":   a.message,
        "detail":    a.detail,
        "read":      a.read,
    } for a in rows]

def get_alerts_for_user(db: Session, user_id: int, limit: int = 100) -> list[dict]:
    """
    Return global alerts annotated with per-user read state.
    If the user has a watchlist, filter alerts to watchlist symbols only.
    """
    watchlist_symbols = [
        row.symbol
        for row in db.query(WatchlistItem).filter_by(user_id=user_id).all()
    ]

    query = db.query(Alert)
    if watchlist_symbols:
        query = query.filter(Alert.symbol.in_(watchlist_symbols))

    rows = query.order_by(Alert.timestamp.desc()).limit(limit).all()

    result = []
    for a in rows:
        state = db.query(UserAlertState).filter_by(user_id=user_id, alert_id=a.id).first()
        result.append({
            "id": a.id,
            "timestamp": a.timestamp.isoformat() + "Z",
            "symbol": a.symbol,
            "type": a.type,
            "severity": a.severity,
            "message": a.message,
            "detail": a.detail,
            "read": state.read if state else False,
        })
    return result


def mark_alert_read_for_user(db: Session, user_id: int, alert_id: str) -> bool:
    alert = db.query(Alert).filter_by(id=alert_id).first()
    if not alert:
        return False

    state = db.query(UserAlertState).filter_by(user_id=user_id, alert_id=alert_id).first()
    if not state:
        state = UserAlertState(user_id=user_id, alert_id=alert_id, read=True, read_at=datetime.utcnow())
        db.add(state)
    else:
        state.read = True
        state.read_at = datetime.utcnow()

    db.commit()
    return True


def mark_all_read_for_user(db: Session, user_id: int) -> int:
    alerts = get_alerts_for_user(db, user_id, limit=1000)
    count = 0

    for item in alerts:
        state = db.query(UserAlertState).filter_by(user_id=user_id, alert_id=item["id"]).first()
        if not state:
            state = UserAlertState(
                user_id=user_id,
                alert_id=item["id"],
                read=True,
                read_at=datetime.utcnow(),
            )
            db.add(state)
            count += 1
        elif not state.read:
            state.read = True
            state.read_at = datetime.utcnow()
            count += 1

    db.commit()
    return count


def mark_alert_read(db: Session, alert_id: str) -> bool:
    alert = db.query(Alert).filter_by(id=alert_id).first()
    if not alert:
        return False
    alert.read = True
    db.commit()
    return True


def mark_all_read(db: Session) -> int:
    count = db.query(Alert).filter_by(read=False).update({"read": True})
    db.commit()
    return count
